### PR TITLE
Update MongoDBCache to use expiresAt on documents instead of clean task

### PR DESCRIPTION
**Pull request by nsollecito**
The flushInvalid function under certain conditions can cause a collection-level lock, causing the application to queue until the query completes.

In place of the cleanup task, set an expireAfterSeconds index along with a new expireAt timestamp at the document level. Mongo will expire documents when the expireAt time is passed:
https://docs.mongodb.com/manual/tutorial/expire-data/index.html

### CODE REVIEW

**Comment by nsollecito** [comment]
@sjdaniels thanks! One important thing to point out is that for anyone using the cache extension prior to this change will need to purge the Mongo databases they're using for cache, otherwise there will be a situation where the documents created prior to the new expireAt index will never expire. Not sure if there might be a more elegant way to handle this transition but if I think of something, I'll open another PR.

**Comment by sjdaniels** [comment]
Yes, I think we should try to come up with some way to deal with this. What about this:

- in MongoDBCache.java createIndexes() method, add a call to a new method `cleanup()` *before* the indexes are added.
- cleanup() would exit if coll.count() is zero
- cleanup() would exit if coll.getIndexes() already contains an index named "expiresAt".
- otherwise, call coll.drop() and continue.

What do you think?

**Comment by nsollecito** [comment]
So after I had this thought, I discovered another place where `flushInvalid ()` is being called [here](https://github.com/lucee/extension-mongodb/blob/master/source/java/src/org/lucee/mongodb/cache/MongoDBCache.java#L154). 

I think this takes care of expiring pre-existing keys since it relies on the prior expires value to expire the key. 

This instance is less problematic because it's specific to the key cache being retrieved so it isn't as likely to produce a lock.

**Comment by sjdaniels** [comment]
Right on. Thanks for the work on this!

**Pull request merged**
